import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import iskandar from "../public/profile-iskandar2.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/port-1.png";
import web2 from "../public/port-2.png";
import web3 from "../public/port-3.png";
import web4 from "../public/port-4.png";
import web5 from "../public/port-5.png";
import web6 from "../public/port6.jpg";
import { AiFillInstagram } from "react-icons/ai";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Iskandar Sholeh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Portofolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/1BC-1fIv1UKzUHln8phxM4l9uMf3EZqji/view?usp=sharing"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Iskandar Sholeh
            </h2>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={iskandar} layout="fill" objectFit="cover" />
            </div>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Fullstack Developer | Associate Android Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              As a Fullstack developer, I&apos;ve a strong understanding of web development, 
              from front-end development with HTML, CSS, and JavaScript to back-end development 
              with PHP and MySQL. I&apos;m also proficient in a variety of other technologies, 
              including Mobile Development, and Cloud Computing.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://github.com/iskandarsh/" target="_blank" rel="noopener noreferrer">
                <AiFillGithub />
              </a>
              <a href="https://www.linkedin.com/in/iskandar-sholeh/" target="_blank" rel="noopener noreferrer">
                <AiFillLinkedin />
              </a>
              <a href="https://www.instagram.com/kconk.iskan/" target="_blank" rel="noopener noreferrer">
                <AiFillInstagram />
              </a>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance developer, I have done remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">IT </span>
              and collaborated with talented people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer a wide range of services, including programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let&apos;s make it a reality.
              </p>
              <h4 className="py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-800 py-1">Text Editor</p>
              <p className="text-gray-800 py-1">Laravel</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Database</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-800 py-1">Meet</p>
              <p className="text-gray-800 py-1">Zoom</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Teamviewer</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white">My Recent Works</h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={web1} />
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={web2} />
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={web3} />
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={web4} />
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={web5} />
            </div>
            <div className="basis-1/3 flex-1">
              <Image className="rounded-lg object-cover" width={"100%"} height={"100%"} layout="responsive" src={web6} />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
